### ISSUE TITLE
Rotate `A` register instructions Z flag is incorrect

### ISSUE THREAD

**Issue by 64kramsystem** [gbdev/gb-opcodes#13]
According to the GameBoy CPU Manual (but this is also verifiable by comparing with the general-register counterparts, e.g. `RLC r`), when performing a rotation (through carry or not) on the `A` register,  the `Z` flag is set according to the result; currently, it's described as being reset.

Instructions: `RRA`, `RLA`, `RRCA`, `RLCA`.

**Comment by avivace** [comment]
Current descriptions are correct. Please check with emulators and ignore that document
