### ISSUE TITLE
Shouldn't some of the operand names be within brackets in the opcodes.json? 

### ISSUE THREAD

**Issue by fizaan** [gbdev/gb-opcodes#14]
For example: 0x02: LD (BC), A

<img width="265" alt="Capture" src="https://user-images.githubusercontent.com/27024481/100035822-0330af80-2dcd-11eb-9579-afe346e9abd9.PNG">

**Comment by tobiasvl** [comment]
The brackets are added when generating the website, if `"immediate"` is `false` (as it is here).

**Comment by ISSOtm** [comment]
I think it's better to expose the "inner" arguments in the JSON, as that saves parsing the strings, and also syntaxes disagree on how to note "dereference" (parens versus brackets).

That said, if this isn't clear enough, it's worth copying @tobiasvl's description somewhere. Maybe in the README?

**Comment by ISSOtm** [comment]
It also saves the bikeshedding of `(bc)` vs `[bc]` or <throw in some other exotic, obscure syntax>.
